### ISSUE TITLE
Create a readme file

### ISSUE THREAD

**Issue by rafaellyra** [leroy-merlin-br/boreal#1]
@Zizaco @GuilhermeGuitte @rplansky  what do you think about a readme file with the instructions to run the project?

**Comment by Zizaco** [comment]
:+1: agreed
Em 22/04/2015 14:41, "Rafael Lyra" <notifications@github.com> escreveu:

**Comment by Zizaco** [comment]
ce657b96c407ac194dbb4dad8f5357c266a21814
