### ISSUE TITLE
Make possible run boreal direct on files

### ISSUE THREAD

**Issue by rafaellyra** [leroy-merlin-br/boreal#2]
I think that boreal needs to also support files as parameters, not just folders. So we can really test each component style file with his view.

cc/ @Zizaco @rplansky @GuilhermeGuitte

**Comment by Zizaco** [comment]
Done: bdddfc1cc9ebe8ed6cd88541b90477d0223f6624
If you point to a file, it will actually uses the file and not try to read it as if it was a directory. :smile:

**Comment by rafaellyra** [comment]
:+1:
